### ISSUE TITLE
cannot find lotus_lca.tax

### ISSUE THREAD

**Issue by Jorisvansteenbrugge** [nioo-knaw/hydra#1]
Hi,

I am trying to run through your pipeline and I managed to get to the point where taxonomic assignment is done.
The rule `lca` is using a taxref file [/data/db/pr2/gb203/lotus_lca.tax](https://github.com/nioo-knaw/hydra/blob/master/Snakefile#L678) but I am a bit puzzled as to how this file was created.

Do you have a script for that, or could you tell how the format of that file is defined?

Thanks in advance!

**Comment by mdehollander** [comment]
Hi Joris,

Thanks for filling in an issue.
I assume you are using the blast option for classification. You are right  a hardcoded path is used here, that shouldn't be like that. In Hydra the blast option can only be used to classify against the PR2 database.
Note that here also a older release of PR2 has been used. That project got a new repo on github with update code: https://github.com/pr2database/pr2database. The file that has been used here as input is the qiime formatted taxonomy file of PR2, which was downloaded on february 2015.
Then this file was formatted:
```
sed 's/Eukaryota;//g' < qiime_gb203_taxo.txt > qiime_gb203_taxo_7levels.txt
python2.7 ../../Silva/123/Misc_Code/SILVA_to_RDP/prep_silva_taxonomy_file.py qiime_gb203_taxo_7levels.txt lotus_lca.tax
```

It looks like:
```
AB353770.1.1740_U       D_0__Alveolata;D_1__Dinophyta;D_2__Dinophyceae;D_3__Dinophyceae_X;D_4__Dinophyceae_XX;D_5__Peridiniopsis;D_6__Peridiniopsis_kevei
KC672520.1.1801_U       D_0__Opisthokonta;D_1__Fungi;D_2__Ascomycota;D_3__Pezizomycotina;D_4__Leotiomycetes;D_5__Leotiomycetes_X;D_6__Leotiomycetes_X_sp.
AY584669.1.2159_R       D_0__Opisthokonta;D_1__Fungi;D_2__Ascomycota;D_3__Pezizomycotina;D_4__Arthoniomycetes;D_5__Simonyella;D_6__Simonyella_variegata
```

What database are you as input? If you are using the newer release of PR2, a different tax for the lca step should be used. I need to make this into an option you can specify in the config file.

Let me know if this helps you.

P.S.
You have been at NIOO isn't it?
